
trigger: none 
pool: ivr-stage-va
    
resources:
  containers:
 - container: terraform_image_container1
   image: $(terraform_image)
 - container: terraform_image_container2
   image: $(terraform_image)

jobs:
- job: RunInContainer
  pool:
    vmImage: 'ubuntu-latest'

  strategy:
    matrix:
      terraform1:
        containerResource: terraform_image_container1
      terraform2:
        containerResource: terraform_image_container1


  container: $[ variables['containerResource'] ]

  steps:
  - script: printenv

