
trigger: none
pool: 
    vmImage: 'ubuntu-latest'
    
resources:
  containers:
  - container: centlatest
    image: centos:latest
    
# root scope for var template
variables:
- template: /variables/global_vars.yml

stages:
- stage: validate_jdk_preview_lab
  jobs:
  - job: validate_jdk_preview_lab 
    displayName: Validate Preview Lab Pipeline Run Results
    pool: server
    steps:
    - task: ManualValidation@0
      timeoutInMinutes: 1440 # task times out in 1 day
      inputs:
        notifyUsers: |
          mehrdad.hazeghi@nuance.com
        instructions: 'Important: Activate ONLY AFTER confirming the Lab pipeline has run and verifying the run results/logs!!!'
        onTimeout: 'resume'

- stage: RunInContainerStage1
  condition: succeeded()
  dependsOn: validate_jdk_preview_lab
  jobs:
  - job: RunInContainerJob1
    timeoutInMinutes: 1
    steps:
    - script: |
        echo "RunInContainerStage1 RunInContainerStage1 RunInContainerStage1 RunInContainerStage1 RunInContainerStage1 RunInContainerStage1"

- stage: RunInContainerStage2
  jobs:
  - job: RunInContainerJob2
    timeoutInMinutes: 1
    steps:
    - script: |
        echo "RunInContainerStage2 RunInContainerStage2 RunInContainerStage2 RunInContainerStage2 RunInContainerStage2 RunInContainerStage2"

