trigger: none
pool: 
    vmImage: 'ubuntu-latest'
    
resources:
  containers:
  - container: centlatest
    image: centos:latest
    
# root scope for var template
variables:
- template: /variables/global_vars.yml

stages:
- stage: RunInContainerStage
  jobs:
  - job: RunInContainerJob
    steps:
    - script: printenv
