trigger: none

# root scope for var template
variables:
- template: /variables/global_vars.yml

pool: 
    vmImage: 'ubuntu-latest'
    
container: docker:latest

steps:
- script: |
    echo "in container ---------------------------------"
    pwd
    ls -ltR
    ps -edaf
    docker ps
    echo ${{ variables.TIME_ZONE }}
    echo "done"
