trigger: none

# root scope for var template
#  variables:
#  - template: /variables/global_vars.yml

pool: 
    vmImage: 'ubuntu-latest'
    
container: ubuntu:18.04

steps:
- script: echo " container"
