
trigger: none 
pool: ivr-stage-va
    
resources:
  containers:
  - container: terraform_image_container1
    image: artifactory-va.staging.nod.nuance.com:8443/infra-docker-repo-virtual/terraform:1.1.9-0.0.67
  - container: terraform_image_container2
    image: artifactory-va.staging.nod.nuance.com:8443/infra-docker-repo-virtual/terraform:1.1.9-0.0.67

jobs:
- job: RunInContainer

  strategy:
    matrix:
      terraform1:
        containerResource: terraform_image_container1
      terraform2:
        containerResource: terraform_image_container1


  container: $[ variables['containerResource'] ]

  steps:
  - script: printenv

