trigger: none

# root scope for var template
variables:
- template: /variables/global_vars.yml

pool: 
    vmImage: 'ubuntu-latest'
    
container: centos:latest

steps:
- script: |
    echo "in container ---------------------------------"
    pwd
    ls -ltR
    ps -edaf
    echo ${{ variables.TIME_ZONE }}
    curl ${{ variables.APACHE_HTTPD_MIRROR_PATH }} | grep -oP '(?<=>httpd-).*(?=.tar.bz2)' > mirror_htppd_list_file
    cat ./mirror_htppd_list_file
    latest_httpd_release_on_mirror_repo=`sort -V mirror_htppd_list_file | tail -1`
    echo ${latest_httpd_release_on_mirror_repo}
    echo "done"
    echo $(Pipeline.Workspace) # /__w/1
    echo build directory $(Agent.BuildDirectory)
