trigger: none

# root scope for var template
variables:
- template: /variables/global_vars.yml

pool: 
    vmImage: 'ubuntu-latest'
    
container: centos:latest

jobs:
- job: container_job
  steps:
  - script: echo "in container ---------------------------------"
